### PR TITLE
Fix GetName failure after reading past end of results. Fixes #24

### LINKED ISSUE #24: InvalidOperationException("There is no current result set.") - reader.GetName(0)
Calling reader.GetName(0) throws "InvalidOperationException". The source of the exception is in the function VerifyHasResult. The state of the reader is "State.AlreadyReadFirstRow".
 
```
		private void VerifyHasResult()
		{
			VerifyNotDisposed();
			if (m_state != State.ReadResultSetHeader && m_state != State.ReadingRows && m_state != )
				throw new InvalidOperationException("There is no current result set.");
		}
```

### PR DESCRIPTION
**Pull request by bgrainger**
Change exception type to match official connector.

### CODE REVIEW

**Comment by ejball** [comment]
Consider adding a C# comment to explain why you're violating the framework guidelines by throwing that exception.

**Comment by bgrainger** [comment]
It's what the documentation specifies: https://msdn.microsoft.com/en-us/library/system.data.idatarecord.getname.aspx

**Comment by ejball** [comment]
How about that! Never mind me.

**Comment by bgrainger** [comment]
It's certainly not what I expected (see my original code). Also, the documentation doesn't specify what exception to throw after `NextResultAsync` returns `false`; I match the official connector but `IndexOutOfRangeException` definitely feels wrong.

**Pull request merged**
