### PR TITLE
Fixed GetGuid() parsing issue

### PR DESCRIPTION
**Pull request by Kagamine**
@bgrainger

### CODE REVIEW

**Comment by bgrainger** [comment]
Hi, thanks for opening a PR.

Can you concisely describe the problem this is solving? Tests that demonstrate the bug would be ideal.

**Comment by bgrainger** [comment]
f1f9de1b26955eb8d0f11a0d59e11721e5e3ca2c changed the indentation (and line endings?), making this PR difficult to review; please revert.

(Also, I'm curious: which editor are you using? I tried to create `.gitattributes` and `.editorconfig` to avoid this problem, but it doesn't seem to have helped.)

**Comment by Kagamine** [comment]
Must the GUID field be `char(36)`?

In Pomelo.EntityFrameworkCore.MySql, GUIDs has been defined as `char(38)`, it caused an exception:

```
   at MySql.Data.MySqlClient.MySqlDataReader.GetGuid(Int32 ordinal)
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at YuukoBlog.Controllers.BaseController.Prepare() 位置 C:\Users\1\Documents\GitHub\YuukoBlog-NETCore-MySql\src\YuukoBlog\Controllers\BaseController.cs:行号 70
   at Microsoft.AspNetCore.Mvc.BaseController.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionFilter.<OnActionExecutionAsync>d__4.MoveNext()
```

**Comment by bgrainger** [comment]
> GUIDs has been defined as char(38)

OK, I'll have to take a look into how MySql.Data processes those and ensure that this is compatible.

**Comment by Kagamine** [comment]
https://github.com/bgrainger/MySqlConnector/blob/master/src/MySqlConnector/MySqlClient/MySqlDataReader.cs#L419

**Comment by Kagamine** [comment]
MySqlDataReader:
```c#
        public override Guid GetGuid(int ordinal)
        {
            return (Guid)GetValue(ordinal);
        }
```

the conversion thrown the exception

**Comment by Kagamine** [comment]
Close this as it did not fixed anything

**Comment by bgrainger** [comment]
I think I understand the problem you're running into and I've opened #48 to track it.

**Pull request closed without merging**
